[package]
name = "color-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
fast-srgb8 = "1.0.0"
itertools = "0.12.1"
