[package]
name = "palette-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "0.1.46"
regex = "1.10.4"
svg = "0.16.0"
lib = { path = "../lib" }
